name: I2P-Daemon-GUI
options:
  bundleIdPrefix: com.example
packages: {}
targets:
  i2pd-gui:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/i2pd-gui
    buildSettings:
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      PRODUCT_BUNDLE_IDENTIFIER: com.i2pd.daemon-gui
      CODE_SIGN_IDENTITY: ""
      PRODUCT_NAME: I2P-GUI
      INFOPLIST_FILE: Info.plist
    info:
      path: Info.plist
      properties:
        CFBundleIdentifier: com.i2pd.daemon-gui
        CFBundleName: I2P Daemon GUI
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundleDisplayName: I2P GUI
        LSApplicationCategoryType: "public.app-category.network"
        LSMinimumSystemVersion: "14.0"
        CFBundleDocumentTypes: []
